apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - config-secret.yaml
  - daemonset.yaml
  - serviceaccount.yaml


