apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 9.5.2
  name: grafana-datasources
  namespace: default
stringData:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access": "proxy",
                "editable": true,
                "name": "Prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-k8s:9090",
                "version": 1,
                "prometheusVersion": "> 2.40.x"
            },
            {
                "access": "proxy",
                "editable": true,
                "name": "Loki",
                "orgId": 1,
                "type": "loki",
                "url": "http://loki:3100",
                "jsonData": {
                  "httpHeaderName1": "X-Scope-OrgID",
                },
                "secureJsonData": {
                  "httpHeaderValue1": "1",
                }
            }
        ]
    }
